### ISSUE TITLE
"iotcModelId" details in provisioning_payload

### ISSUE THREAD

**Issue by ghost** [iot-for-all/Iot_Central_Python_Sample#1]
Hi 
I was wondering that in iot_central_sample.py file how do we come to know the key "iotcModelId" for assigning a template to the device during device registration in line number 226
 `provisioning_device_client.provisioning_payload = '{"iotcModelId":"%s"}' % (model_identity)`

Can we also send as a payload the name of the device along with model identity..?

If yes how can we do it...?

**Comment by firedog1024** [comment]
You can get the value for iotcModelId from the IoT Central application by selecting the "device template" -> clicking the device template you want the id for  -> then click View identity and copy the value in interface @id

![image](https://user-images.githubusercontent.com/5815016/106209890-b5dd0f80-617a-11eb-9887-af96b7bbb94b.png)

Right now you cannot specify the device name in the payload but that is a feature that is being considered for addition as others have noted it would be useful.
